### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rodolfoinfantini** [E-boi/voice-events#1]
It just works on the test in the settings but when I or someone left a channel it just does nothing

**Comment by NyxIsBad** [comment]
^ plugin currently non functional. worth noting that the betterdiscord version broke too

**Comment by NyxIsBad** [comment]
I think bumping this now is somewhat appropriate, since it hasn't worked for the past five months

**Comment by NyxIsBad** [comment]
Zerthox's BD plugin now works with BDcompat actually so you may want to switch to using that @SirVoRaK

**Comment by rodolfoinfantini** [comment]
> 
> 
> Zerthox's BD plugin now works with BDcompat actually so you may want to switch to using that @SirVoRaK

Oooh it is working, it is just my favorite plugin btw, I had already given up trying, thank you.

**Comment by E-boi** [comment]
nice i dont plan on maintaining this plugin anymore sorry
